# Generated by Django 5.2.4 on 2025-08-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(choices=[('mobile money', 'Mobile Money')], max_length=100)),
                ('status', models.CharField(choices=[('in-progress', 'In-progress'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('farmer_to_coop', 'Farmer to Cooperative'), ('coop_to_supplier', 'Cooperative to Supplier')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lending_Record',
            fields=[
                ('lending_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CooperativePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
            ],
            bases=('payments.payment',),
        ),
    ]
