# Generated by Django 5.2.4 on 2025-08-04 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinery', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='lending_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.lending_record'),
        ),
        migrations.AddField(
            model_name='lending_record',
            name='approved_by',
            field=models.ForeignKey(limit_choices_to={'type': 'machine_supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='approved_lendings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lending_record',
            name='borrower',
            field=models.ForeignKey(limit_choices_to={'type': 'cooperative'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lending_record',
            name='machinery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.machinery'),
        ),
        migrations.AddField(
            model_name='cooperativepayment',
            name='cooperative',
            field=models.ForeignKey(limit_choices_to={'type': 'cooperative'}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooperativepayment',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'type': 'machine_supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='cooperative',
            field=models.ForeignKey(limit_choices_to={'type': 'cooperative'}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_farmer_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
