# Generated by Django 4.2.23 on 2025-07-21 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cooperative', 'Cooperative'), ('extension_officer', 'Extension Officer'), ('farmer', 'Farmer'), ('machine_supplier', 'Machine Supplier')], max_length=30)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('cooperative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('officer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cooperative', models.ForeignKey(blank=True, limit_choices_to={'type': 'cooperative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.user')),
            ],
        ),
    ]
