# Generated by Django 4.2.23 on 2025-07-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cooperative_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farmer_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='officer_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supplier_name',
        ),
    ]
