# Generated by Django 5.2.4 on 2025-08-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
