# Generated by Django 4.2.23 on 2025-06-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0002_rename_cooperatives_cooperative'),
        ('extension_officer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension_Officer',
            fields=[
                ('extension_id', models.AutoField(primary_key=True, serialize=False)),
                ('officer_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('cooperative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative')),
            ],
        ),
        migrations.DeleteModel(
            name='Extension_Officers',
        ),
    ]
