# Generated by Django 4.2.23 on 2025-06-24 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extension_officer', '0002_extension_officer_delete_extension_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension_officer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
