# Generated by Django 4.2.23 on 2025-06-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0002_rename_cooperatives_cooperative'),
        ('farmers', '0002_rename_farmers_farmer'),
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending_Record',
            fields=[
                ('lending_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative')),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
                ('machinery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.machinery')),
            ],
        ),
    ]
