# Generated by Django 5.2.4 on 2025-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_record',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=100),
        ),
    ]
