# Generated by Django 5.2.4 on 2025-07-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending_records', '0002_alter_lending_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending_record',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In_use')], max_length=100),
        ),
    ]
