# Generated by Django 5.2.3 on 2025-06-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extension_officer', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer_Visit',
            fields=[
                ('visits_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension_officer.extension_officer')),
            ],
        ),
    ]
