# Generated by Django 4.2.23 on 2025-06-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0002_rename_farmers_farmer'),
        ('extension_officer', '0002_extension_officer_delete_extension_officers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer_Visit',
            fields=[
                ('visits_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension_officer.extension_officer')),
            ],
        ),
    ]
