# Generated by Django 5.2.4 on 2025-07-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer_Visit',
            fields=[
                ('visits_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('farmer_id', models.ForeignKey(limit_choices_to={'type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_visits', to='users.user')),
                ('officer_id', models.ForeignKey(limit_choices_to={'type': 'extension_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_visits', to='users.user')),
            ],
        ),
    ]
