# Generated by Django 4.2.23 on 2025-06-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('farmers', '0001_initial'),
        ('machine_supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperatives')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CooperativePayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperatives')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_supplier.machine_suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
