# Generated by Django 5.2.4 on 2025-07-16 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(choices=[('mobile money', 'Mobile Money')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('farmer_to_coop', 'Farmer to Cooperative'), ('coop_to_supplier', 'Cooperative to Supplier')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CooperativePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
                ('cooperative', models.ForeignKey(limit_choices_to={'type': 'cooperative'}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(limit_choices_to={'type': 'machine_supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
                ('cooperative', models.ForeignKey(limit_choices_to={'type': 'cooperative'}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_farmer_payments', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(limit_choices_to={'type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_payments', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('payments.payment',),
        ),
    ]
