# Generated by Django 4.2.23 on 2025-07-20 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lending_records', '__first__'),
        ('users', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AddField(
            model_name='payment',
            name='lending_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lending_records.lending_record'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile money', 'Mobile Money')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
                ('cooperative', models.ForeignKey(limit_choices_to={'type': 'cooperative'}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_farmer_payments', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(limit_choices_to={'type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_payments', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='CooperativePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
                ('cooperative', models.ForeignKey(limit_choices_to={'type': 'cooperative'}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(limit_choices_to={'type': 'machine_supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
            bases=('payments.payment',),
        ),
    ]
