# Generated by Django 4.2.23 on 2025-06-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_rename_farmers_farmer'),
        ('cooperatives', '0002_rename_cooperatives_cooperative'),
        ('machine_supplier', '0003_machine_supplier_user'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('farmer_to_coop', 'Farmer to Cooperative'), ('coop_to_supplier', 'Cooperative to Supplier')], max_length=20)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cooperatives.cooperative')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='farmers.farmer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='machine_supplier.machine_supplier')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.RemoveField(
            model_name='farmerpayment',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='farmerpayment',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='CooperativePayment',
        ),
        migrations.DeleteModel(
            name='FarmerPayment',
        ),
    ]
