# Generated by Django 5.2.4 on 2025-07-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending_records', '0003_alter_lending_record_status'),
        ('payments', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lending_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lending_records.lending_record'),
        ),
    ]
