# Generated by Django 4.2.23 on 2025-06-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth_Tokens',
            new_name='Auth_Token',
        ),
    ]
