# Generated by Django 5.2.4 on 2025-07-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('machinery_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('In_use', 'in_use')], max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Machinery_Tracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('activity', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer_Visit',
            fields=[
                ('visits_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
