# Generated by Django 5.2.4 on 2025-07-24 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='added_by',
            field=models.ForeignKey(limit_choices_to={'type__in': ['cooperative', 'machine_supplier']}, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinery',
            name='supplier_id',
            field=models.ForeignKey(limit_choices_to={'type': 'machine_supplier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_supplied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinery_tracking',
            name='machinery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.machinery'),
        ),
        migrations.AddField(
            model_name='officer_visit',
            name='farmer_id',
            field=models.ForeignKey(limit_choices_to={'type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officer_visit',
            name='officer_id',
            field=models.ForeignKey(limit_choices_to={'type': 'extension_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
