# Generated by Django 5.2.3 on 2025-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('machinery_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
