# Generated by Django 4.2.23 on 2025-07-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('machinery_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=100)),
                ('created_at', models.DateTimeField()),
                ('added_by', models.ForeignKey(limit_choices_to={'type__in': ['cooperative', 'machine_supplier']}, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_added', to='users.user')),
                ('supplier_id', models.ForeignKey(limit_choices_to={'type': 'machine_supplier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_supplied', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Officer_Visit',
            fields=[
                ('visits_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('farmer_id', models.ForeignKey(limit_choices_to={'type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_visits', to='users.user')),
                ('officer_id', models.ForeignKey(limit_choices_to={'type': 'extension_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_visits', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Machinery_Tracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('activity', models.TextField(null=True)),
                ('machinery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.machinery')),
            ],
        ),
    ]
