<<<<<<< Updated upstream
# Generated by Django 4.2.22 on 2025-06-22 12:03
=======
# Generated by Django 5.2.3 on 2025-06-24 19:01
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('machinery_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
