# Generated by Django 5.2.4 on 2025-07-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='added_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'cooperative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='machinery.machinery'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=100),
        ),
    ]
