# Generated by Django 5.2.4 on 2025-07-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_alter_machinery_added_by_alter_machinery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='added_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
