# Generated by Django 5.2.4 on 2025-07-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0004_alter_machinery_added_by'),
        ('users', '0002_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='supplier_id',
            field=models.ForeignKey(limit_choices_to={'type': 'machine_supplier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_supplied', to='users.user'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='added_by',
            field=models.ForeignKey(limit_choices_to={'type__in': ['cooperative', 'extension_officer']}, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_added', to='users.user'),
        ),
    ]
