# Generated by Django 5.2.4 on 2025-07-17 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0005_machinery_supplier_id_alter_machinery_added_by'),
        ('users', '0002_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='added_by',
            field=models.ForeignKey(limit_choices_to={'type__in': ['cooperative', 'machine_supplier']}, on_delete=django.db.models.deletion.CASCADE, related_name='machineries_added', to='users.user'),
        ),
    ]
