# Generated by Django 5.2.3 on 2025-06-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('farmers', '0001_initial'),
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending_Records',
            fields=[
                ('lending_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperatives')),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmers')),
                ('machinery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinery.machinery')),
            ],
        ),
    ]
