# Generated by Django 5.2.3 on 2025-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Tokens',
            fields=[
                ('tokens_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
    ]
