# Generated by Django 4.2.23 on 2025-06-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine_Suppliers',
            new_name='Machine_Supplier',
        ),
    ]
