<<<<<<< Updated upstream
# Generated by Django 5.2.3 on 2025-06-22 12:05
=======
# Generated by Django 5.2.3 on 2025-06-24 19:01
>>>>>>> Stashed changes

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
<<<<<<< Updated upstream
                ('cooperative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperatives')),
=======
                ('cooperative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> Stashed changes
            ],
        ),
    ]
